### ISSUE TITLE
Invalid default position

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#1]
![Screenshot_1583898834](https://user-images.githubusercontent.com/40521292/76380908-1f86dc00-6365-11ea-9402-1dcb7ed9a877.png)

**Comment by ArtemGord1728** [comment]
https://github.com/ArtemGord1728/WeatherApp/commit/8e9d59061b3de93456d83ada71dd4a4690b88408
