### ISSUE TITLE
NetworkUtils

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#11]
Класс вообще не используется

https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/network/NetworkUtils.java#L7

**Comment by ArtemGord1728** [comment]
Этот класс пока оставлю, создавал его с перспективой на проверки подключения к Интернету
