### ISSUE TITLE
ListInfo

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#12]
Название не говорит о предназначении класса

https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/model/ListInfo.java#L7

**Comment by ArtemGord1728** [comment]
https://github.com/ArtemGord1728/WeatherApp/commit/4bfc451db1c3e3676e992d1bfc166e0af9c82d8f
