### ISSUE TITLE
ListCitiesFragment GPSTracker

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#14]
Для чего GPSTracker в ListCitiesFragment?

https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/ui/cities_list/ListCitiesFragment.java#L44

**Comment by ArtemGord1728** [comment]
https://github.com/ArtemGord1728/WeatherApp/commit/dcd502ea15bfb20925e3b137b25543368d5da343
