### ISSUE TITLE
Retrofit

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#16]
Не должен создаваться instance retrofit-а в каждом фрагменте.

https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/ui/cities_list/ListCitiesFragment.java#L55-L56

**Comment by ArtemGord1728** [comment]
Оставил инициализацию только в MapFragment, в ListCitiesFragment - убрал
