### ISSUE TITLE
Повторный запрос

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#17]
В списке не должно быть запроса, использовать результат, полученный на MapFragment.

https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/ui/cities_list/ListCitiesFragment.java#L70-L94

**Comment by ArtemGord1728** [comment]
https://github.com/ArtemGord1728/WeatherApp/commit/f1edb3409817d83cc2ffab0ba65c361ae6161d04
