### ISSUE TITLE
MapFragment

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#18]
1. Удалить неиспользующиеся переменные.
2. Делать проверку на activity != null, переменная isGranted не нужна, объединить условия в один блок if
https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/ui/map/MapFragment.java#L90-L102
3. Switch излишен, пустой цикл
https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/ui/map/MapFragment.java#L104-L120
4. Никаких `setRetainInstance(true)`!
https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/ui/map/MapFragment.java#L129
5. Использовать строковые ресурсы
https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/ui/map/MapFragment.java#L198-L202

**Comment by ArtemGord1728** [comment]
https://github.com/ArtemGord1728/WeatherApp/commit/353c06722cbd5c5118762ddf50b9b4933e2231d7
