### ISSUE TITLE
activity_main.xml

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#19]
Говорил же не использовать NavGraph
https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/res/layout/activity_main.xml#L20-L30

Для чего задавать margin* = 0dp?
https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/res/layout/activity_main.xml#L12-L13

**Comment by ArtemGord1728** [comment]
Насчёт первого - буду учиться пользоваться NavGraph, поэтому и создал)))
Насчёт второго - вот)
https://github.com/ArtemGord1728/WeatherApp/commit/98ae4566976a30aebad1d43f96b73016cbf5aad6

**Comment by DaniilPavlenko** [comment]
В таком случае фрагмент не должен пересоздаваться при переключении на другой
