### ISSUE TITLE
fragment_list_cities.xml

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#22]
Нет смысла использовать ConstraintLayout в данном случае
https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/res/layout/fragment_list_cities.xml#L1-L13

**Comment by ArtemGord1728** [comment]
https://github.com/ArtemGord1728/WeatherApp/commit/00eb49e336b5d1a3e3256d849f86007d9b561b8c
