### ISSUE TITLE
fragment_map.xml

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#23]
Тоже самое, нет смысла использовать ConstraintLayout
https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/res/layout/fragment_map.xml#L1-L13

**Comment by ArtemGord1728** [comment]
https://github.com/ArtemGord1728/WeatherApp/commit/48b8b74756c2ffc32aa3728c174b1489b5887e41
