### ISSUE TITLE
Логика не соответствует названию функции

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#3]
Здесь ты не должен устанавливать позицию карты и как-то  менять ее состояние.
Функция у тебя должна вернуть результат в виде широты и долготы, а в месте вызова уже применять полученные данные.

https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/common/MapsStateUtil.java#L31-L46

**Comment by ArtemGord1728** [comment]
https://github.com/ArtemGord1728/WeatherApp/commit/0a6b04c9f8d2e3a8b56807ddfd53de436e21e7ec
