### ISSUE TITLE
Сохранение маркеров

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#4]
Сохранение маркеров таким способом излишне.

https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/common/MapsStateUtil.java#L48-L68

**Comment by ArtemGord1728** [comment]
Но все таки работает)

**Comment by DaniilPavlenko** [comment]
Решение можно растянуть и на 3000 строк. Так что это не решение

**Comment by ArtemGord1728** [comment]
Можешь уточнить пожалуйста, что тебе не "по душе"?

**Comment by DaniilPavlenko** [comment]
Маркеры не нужно хранить в долговременной памяти, их хранишь только во время активного приложения. Поэтому и говорю, что TinyDB тебе не нужен в этом проекте, ты не будешь хранить большой объем данных в долговременной памяти, если вообще будешь...
