### ISSUE TITLE
SharedPrefUtils

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#5]
Никаким образом не упрощает взаимодействие с Shared Preferences.
Придумать что-то другое, чтобы избавиться от постоянной передачи SharedPreferences.Editor и SharedPreferences в качестве аргументов.

https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/common/SharedPrefUtils.java#L5-L31

**Comment by ArtemGord1728** [comment]
https://github.com/ArtemGord1728/WeatherApp/commit/1729cc05e68e64e8504ca9a20f2346984373ea57
