### ISSUE TITLE
TinyDB.java

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#6]
Удалить, нет необходимости

https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/common/TinyDB.java#L24

**Comment by ArtemGord1728** [comment]
Есть необходимость: 
https://github.com/ArtemGord1728/WeatherApp/commit/1729cc05e68e64e8504ca9a20f2346984373ea57
