### ISSUE TITLE
@SerializedName(*)

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#7]
Для чего используется @SerializedName(*)?
Относится ко всем моделям

https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/model/Coordinate.java#L5-L27

**Comment by ArtemGord1728** [comment]
Можно указывать имя сериализуемого/десериализуемого поля при парсинге Json или при переводе объекта в Json

**Comment by DaniilPavlenko** [comment]
Попробуй переименовать свойство 
https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/model/Coordinate.java#L7
 в lon2, приложение также корректно работает?

**Comment by ArtemGord1728** [comment]
Нет, не корректно

**Comment by DaniilPavlenko** [comment]
> Нет, не корректно

А должно работать, в этом смысл @SerializedName, найди ошибку.
