### ISSUE TITLE
mContext

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#8]
Хранить Context Activity нельзя в сервисах

https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/network/GPSTracker.java#L33

**Comment by ArtemGord1728** [comment]
https://github.com/ArtemGord1728/WeatherApp/commit/76a49a08e931ced1c2183a44cb505228364165bb
