### ISSUE TITLE
Проверка разрешений

### ISSUE THREAD

**Issue by DaniilPavlenko** [ArtemGord1728/WeatherApp#9]
Сделать проверку разрешений

https://github.com/ArtemGord1728/WeatherApp/blob/0ff6a7f8107117a062ea66056abcf731949d4fad/app/src/main/java/com/weather/app/network/GPSTracker.java#L83-L96

**Comment by ArtemGord1728** [comment]
https://github.com/ArtemGord1728/WeatherApp/commit/7de93d9fcb59bef5358478670c760ffde21091df
